Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2020-05, with the labels that each got.

#35 [ci:component:github.com/gardener/machine-controller-manager:v0.27.0->v0.28.0]
  charts/images.yaml
Labels: needs/ok-to-test

#37 Vendor gardener/gardener@v1.4.1
  Dockerfile
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/healtcheck_actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/utils.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/predicate/predicate.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/pkg/api/extensions/accessor.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_defaults.go
  vendor/github.com/gardener/gardener/pkg/chartrenderer/default.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/github.com/gardener/gardener/test/framework/gomega_utils.go
  vendor/modules.txt
Labels: needs/ok-to-test

#36 Use workqueue backoff
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#38 Prevent errors to be logged multiple times
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: needs/ok-to-test

#39 [ci:component:github.com/gardener/machine-controller-manager:v0.28.0->v0.29.0]
  charts/images.yaml
Labels: needs/ok-to-test

#41 Vendor gardener/gardener@4f4a1db77d90a828d5681ee4a7daab9a920ed3af
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/etcd_types.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/hack/install-requirements.sh
  vendor/github.com/gardener/gardener/hack/update-codegen.sh
  vendor/github.com/gardener/gardener/hack/update-protobuf.sh
  vendor/github.com/gardener/gardener/pkg/api/extensions/accessor.go
  vendor/github.com/gardener/gardener/pkg/api/extensions/utils.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shootstate.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shootstate.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_common.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/pods.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/seedfilter.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/object.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/certificates.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/github.com/huandu/xstrings/convert.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#42 Vendor gardener/gardener@4949b41172cc35f6fecf920d6f7151b24562ae75
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#43 Add missing Service for cloud-controller-manager
  charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/service.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/monitoring, kind/bug, needs/ok-to-test, priority/normal

#44 Vendor gardener/gardener@28def0ceecf15f5c7323cd5e65300adc0b0c81da
  cmd/gardener-extension-provider-packet/app/app.go
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#45 Vendor gardener/gardener@v1.5.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#46 Fix status.lastError.codes for Infrastructure
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#47 Vendor gardener/gardener@v1.5.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/retry.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/modules.txt
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal
