Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2020-09, with the labels that each got.

#74 Cleanup make test
  Makefile
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#73 Add Kubernetes 1.19 note to README.md
  README.md
Labels: area/open-source, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#76 Updated RBAC to allow node/status update by MCM
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#80 adding statefulsets in rbac
  charts/gardener-extension-provider-packet/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#81 Updated packet-cloud-controller deployment
  charts/internal/seed-controlplane/charts/packet-cloud-controller-manager/templates/deployment.yaml
Labels: needs/ok-to-test, priority/normal, reviewed/lgtm
