Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2020-06, with the labels that each got.

#48 [ci:component:github.com/gardener/terraformer:v1.0.0->v1.1.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#50 Vendor gardener/gardener@b50098267f2577d06674903fa20032f1fe44894b
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: area/open-source, kind/bug, needs/ok-to-test, priority/normal

#51 [ci:component:github.com/gardener/machine-controller-manager:v0.29.0->v0.30.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#52 Wait for terraformer before deleting infrastructure
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/predicate/predicate.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go
  vendor/github.com/gardener/gardener/hack/install-requirements.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/apply.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/github.com/gardener/gardener/test/framework/shootcreationframework.go
  vendor/modules.txt
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm

#53 [ci:component:github.com/gardener/terraformer:v1.1.0->v1.2.0]
  charts/images.yaml
Labels: needs/ok-to-test

#54 [ci:component:github.com/gardener/machine-controller-manager:v0.30.0->v0.31.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#56 add rolling update strategy to deployment
  charts/gardener-extension-provider-packet/templates/deployment.yaml
  charts/gardener-extension-provider-packet/values.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/technical-debt, needs/ok-to-test, priority/normal

#57 Delete running terraformer Pods before deleting infrastructure
  pkg/controller/infrastructure/actuator_delete.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, needs/review, priority/normal

#59 [ci:component:github.com/gardener/terraformer:v1.2.0->v1.3.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm
