Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2023-05, with the labels that each got.

#258 Update ccm to 3.6.1
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, platform/equinix-metal

#261 Add schrodit as codeowner
  CODEOWNERS
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal

#260 Adapt `NetworkPolicy`s
  charts/gardener-extension-provider-equinix-metal/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/seed-controlplane/charts/cloud-provider-equinix-metal/templates/service.yaml
  example/controller-registration.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal

#264 Removed unsupported flags for mcm deployment
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/usability, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal
