Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2024-11, with the labels that each got.

#303 Update equinix sdk
  go.mod
  go.sum
  pkg/controller/controlplane/vpn.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/worker/add.go
  pkg/controller/worker/machine_dependencies.go
  pkg/equinixmetal/client/client.go
  pkg/equinixmetal/client/types.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l, platform/equinix-metal

#327 docs: Fix reference to shoot operations documentation
  CONTRIBUTING.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal

#329 fix(ensurer): remove `firstBoot` setting
  pkg/webhook/controlplane/ensurer.go
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/m, platform/equinix-metal

#330 fix(ensurer): add missing equal sign
  pkg/webhook/controlplane/ensurer.go
Labels: area/storage, kind/bug, reviewed/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal
