Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2024-05, with the labels that each got.

#309 Support for Kubernetes v1.30
  README.md
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/review, size/xs, topology/garden, topology/seed, topology/shoot, merge/squash, platform/equinix-metal

#311 [ci:component:github.com/gardener/machine-controller-manager-provider-equinix-metal:v0.7.0->v0.8.0]
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#314 Read new `.spec.pools[].userDataSecretRef` field for worker pool user data
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/s, area/scalability
