Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2025-03, with the labels that each got.

#335 fix: change strategicMergeFrom to MergeFrom for CRD
  pkg/controller/worker/machine_dependencies.go
Labels: area/storage, kind/bug, needs/ok-to-test, needs/review, size/xs, platform/equinix-metal

#328 Drop support for Shoots with Kubernetes version <= 1.26
  README.md
  charts/gardener-extension-provider-equinix-metal/templates/poddisruptionbudget.yaml
  charts/internal/seed-controlplane/charts/cloud-provider-equinix-metal/templates/poddisruptionbudget.yaml
  docs/operations/operations.md
  example/26-cloudprofile.yaml
  example/controller-registration.yaml
  pkg/webhook/controlplane/ensurer_test.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, platform/equinix-metal

#333 [ci:component:github.com/gardener/terraformer:v2.26.0->v2.27.0]
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs
