Repository gardener/gardener-extension-provider-equinix-metal, pull requests merged in 2025-05, with the labels that each got.

#324 Support for Kubernetes v1.31
  Makefile
  README.md
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, topology/garden, topology/seed, topology/shoot, merge/squash, platform/equinix-metal

#339 [ci:component:github.com/gardener/terraformer:v2.27.0->v2.28.0]
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#342 chore(pipeline): set verify image to 1.24.2
  .ci/pipeline_definitions
Labels: kind/enhancement, needs/ok-to-test, size/xs, area/testing, platform/equinix-metal

#347 feat(actions): add dependabot
  .github/dependabot.yml
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, size/xs, platform/equinix-metal

#352 migrate to GitHub-Actions
  .ci/pipeline_definitions
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
Labels: area/delivery, kind/cleanup, needs/review, size/m, platform/equinix-metal

#353 chore(go.mod): bump gardener version to 1.119.0
  .github/ISSUE_TEMPLATE/support.md
  .github/actions/prepare-release/action.yaml
  .github/workflows/build.yaml
  .golangci.yaml
  Dockerfile
  cmd/gardener-extension-provider-equinix-metal/app/app.go
  example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
  example/20-crd-extensions.gardener.cloud_backupentries.yaml
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/20-crd-extensions.gardener.cloud_clusters.yaml
  example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
  example/20-crd-extensions.gardener.cloud_controlplanes.yaml
  example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
  example/20-crd-extensions.gardener.cloud_extensions.yaml
  example/20-crd-extensions.gardener.cloud_infrastructures.yaml
  example/20-crd-extensions.gardener.cloud_networks.yaml
  example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  example/20-crd-resources.gardener.cloud_managedresources.yaml
  example/doc.go
  go.mod
  go.sum
  pkg/apis/config/loader/loader.go
  pkg/controller/worker/add.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/equinixmetal/client/client.go
  pkg/webhook/controlplane/ensurer_test.go
  pkg/webhook/controlplaneexposure/add.go
  pkg/webhook/controlplaneexposure/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: area/open-source, kind/technical-debt, needs/review, reviewed/ok-to-test, size/xl, platform/equinix-metal
